# Generated by Django 5.1.1 on 2024-12-01 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_zone_address_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='area_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='users.area'),
        ),
        migrations.AddField(
            model_name='address',
            name='zone_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='users.zone'),
        ),
    ]
