# Generated by Django 5.1.1 on 2024-11-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cover',
            field=models.ImageField(blank=True, default='stores/covers/default.svg', null=True, upload_to='stores/covers/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, default='stores/logos/default.svg', null=True, upload_to='stores/logos/'),
        ),
    ]
